### PR TITLE
fix #9: make afterConfirm, afterCancel callable

### PR DESCRIPTION
**Pull request by ZacharyRSmith**
@falexandrou , i would appreciate your review of this...i don't know why i can't get any setState callback to work (try it anywhere), but here's a way to fix the bug you reported

### CODE REVIEW

**Comment by ZacharyRSmith** [comment]
see #9 for history

**Comment by ZacharyRSmith** [comment]
before merging, i want to blow away node_modules and reinstall using something other than npm v5...i have a hunch that's doing something weird...

**Comment by falexandrou** [comment]
I think this approach is far cleaner but I'm not yet convinced why we need the `CONFIRM` hook on both `componentDidUpdate` and `componentWillUnmount`. Before jumping to any conclusions, I need to carefully examine this, so the weekend is perfect for this task :) 

As for v5 I haven't had any issues so far but I agree that removing `node_modules` and starting fresh might be a good thing to try out.

**Comment by ZacharyRSmith** [comment]
Oigaboik!! setState()'s callback was not called when i used npm v5, but after reinstalling using yarn it was called.  Of course, it was not called when the component is unmounted, but at least the updater.enqueueSetState accepted a callback.

reason for the `CONFIRM` hook on both `componentDidUpdate` and `componentWillUnmount`:

The `CONFIRM` hook on `componentDidUpdate` is used when NavigationPrompt is not unmounted. Eg, when navigating between /foo and /bar here:

```
          <NavigationPrompt when={true}>
            {({onConfirm, onCancel}) => (
              <div>
                <button onClick={onConfirm}>Confirm</button>
                <button onClick={onCancel}>Cancel</button>
              </div>
            )}
          </NavigationPrompt>
          <div style={{ display: 'flex' }}>
            Nav:
            <Link to="/foo">foo</Link>
            <Link to="/bar">bar</Link>
          </div>
          <Switch>
            <Route path="/foo" render={() => (<div>foo</div>)}/>
            <Route path="/bar" render={() => (<div>bar</div>)}/>
          </Switch>
```

but, the hook in `componentDidUpdate` may not be called if the component is unmounted, hence the hook in `componentWillUnmount`.

i think we're safe from the hook being called twice after one confirm?

**Comment by ZacharyRSmith** [comment]
closes #13

**Pull request merged**
